### ISSUE TITLE
Undefined method 'refresh'

### ISSUE THREAD

**Issue by kevintraver** [koraktor/braumeister.org#33]
When running `rake db:seed` on a freshly cloned repository, I get the following error:

`NoMethodError: undefined method 'refresh' for #<Repository:0x007ff9033f0af8>`

**Comment by koraktor** [comment]
Good catch. The following line is missing inside `db/seeds.rb`:

```ruby
require 'repository_import'
```

**Comment by kevintraver** [comment]
Still getting the same error.

**Comment by koraktor** [comment]
Sorry, didn't test that fix as I don't have my development machine at hand.

You will also have to add the following line as the first one inside the loop:

```ruby
repo.extend RepositoryImport
```
