### ISSUE TITLE
Formula version badges

### ISSUE THREAD

**Issue by zbeekman** [koraktor/braumeister.org#35]
See also, https://github.com/Homebrew/homebrew/issues/48299

It would be great for package authors to be able to include badges on their Github `README.md`s indicating which version of their package is currently available via Homebrew. Such badges exist for other package managers like PYPI. It seems that braumeister.org may be the correct service to provide at least a `GET` method to fetch the current version of a package, if not full on svg badge support.

**Comment by koraktor** [comment]
A minimalistic API for the current formula versions is no problem. Is that everything that’s required for shields.io?

**Comment by zbeekman** [comment]
In short: I have no idea. But it's a step in the right direction. Let's see if anyone responds to the issue over there, and what they have to say. If all else fails I could roll my own using a simple API. I'm guessing it's a necessary condition, but I'm not sure if it's sufficient. I'll try to dig around some more.

**Comment by wilmoore** [comment]
> Is that everything that’s required for shields.io?

@koraktor Yes...that is all that is needed. For example, badges for npm packages are based on API calls such as:

```shell
❯ curl https://api.npmjs.org/downloads/point/last-month/selectn
{"downloads":37834,"start":"2015-12-30","end":"2016-01-28","package":"selectn"}

❯ curl https://registry.npmjs.org/-/package/selectn/dist-tags
{"latest":"0.10.0"}
```

**Comment by koraktor** [comment]
This is now available:

http://braumeister.org/formula/git/version
http://braumeister.org/repos/Homebrew/homebrew-versions/formula/tomcat7/version

**Comment by zbeekman** [comment]
:tada: :clap:

**Comment by zbeekman** [comment]
> Is that everything that’s required for shields.io?
> Sebastian Staudt Yes...that is all that is needed. For example, badges for npm packages are based on API calls such as:
> 
> ❯ curl https://api.npmjs.org/downloads/point/last-month/selectn
> {"downloads":37834,"start":"2015-12-30","end":"2016-01-28","package":"selectn"}
> 
> ❯ curl https://registry.npmjs.org/-/package/selectn/dist-tags
> {"latest":"0.10.0"}
> REF: https://github.com/badges/shields/blob/master/server.js#L1341-L1523

If someone would put in a PR with shields.io that would be great. I am contemplating teaching myself enough JS to hack away at https://github.com/badges/shields/blob/master/server.js but I think someone else could do it much more expediently than I could.

**Comment by olivierlacan** [comment]
This is excellent. :clap:

**Comment by wilmoore** [comment]
:+1:

**Comment by gep13** [comment]
I have just added a basic PR for this functionality here: https://github.com/badges/shields/pull/675 Hopefully this will get pulled in.

**Comment by koraktor** [comment]
Thanks @gep13.

Example for Git: [![Git](https://img.shields.io/homebrew/v/git.svg)](http://braumeister.org/formula/git)

**Comment by zbeekman** [comment]
@gep13 you have gittip or flatr? I'd shoot you a few bucks for beer or coffee! :tada:

**Comment by gep13** [comment]
@zbeekman thank you for the very kind offer, but this really isn't required.  I needed this for one of my own projects, so was happy to do it, but thank you, I very much appreciate the offer :smile:
