### ISSUE TITLE
Option to search all or a selection of Homebrew repos at once

### ISSUE THREAD

**Issue by Niels-NTG** [koraktor/braumeister.org#37]
I'm a frequent user of braumeister. Still I quite often can't find the things I'm looking for. Sometimes that's simply because they don't exist, but often it because they are in `homebrew-science`, `homebrew-games`, … instead of the default tap. Why doesn't the search bar have a filter option where can check and uncheck certain repositories so you can search in multiple at once? Perhaps their's a really good reason for that. But I really like to have this option nonetheless.

**Comment by koraktor** [comment]
Thanks for your feedback.
This is already covered by issue #11.
Although this is a pretty old issue, I'd love to work on this soon.
