### ISSUE TITLE
Implement an API or database dump

### ISSUE THREAD

**Issue by AMDmi3** [koraktor/braumeister.org#45]
I couldn't find anything like that for homebrew, and braumeister seems like the project it would be simple to implement on. What I need is an API or a database dump in some machine readable format (json, xml) which allows to get information (name, version, desc, homepage, url) on all homebrew formulae at once in an easy way. I need it to add homebrew support to https://repology.org.

**Comment by vadi2** [comment]
I'd love to see something like this happen since repology.org is for the desktop as caniuse.com is for the web, the advantages are obvious.

**Comment by AMDmi3** [comment]
It turns out that just a regularly updated downloadable dump of ```brew info --json=v1 --all``` is quite enough for repology. The only thing it doesn't have are download URLs (which are present in original formulas), but these are completely optional (though if they are present, it'd allow repology feature of dead link detection to work for homebrew).

My guess it's not that hard to introduce to braumeister update process. Unfortunately I can't do it myself as homebrew is not portable and one cannot work with in on non-MacOSX.

**Comment by koraktor** [comment]
I think I don't want an API that's able to deliver all data to an external client, i.e. piggybacking on our work to extract this data and wasting additional resources to provide the API.
I don't have a problem with specialized APIs like the one for shields.io.

But feel free to have a look at the import code to see how it's done.

**Comment by koraktor** [comment]
@AMDmi3 braumeister.org is running on Linux hosts itself (Heroku to be more specific). So we're not able to provide the output of a `brew` command.

**Comment by AMDmi3** [comment]
Got it, thank you!
