### ISSUE TITLE
Repository name being nil on show.html leads to broken commit URLs

### ISSUE THREAD

**Issue by zmwangx** [koraktor/braumeister.org#49]
Take http://braumeister.org/formula/emacs for example. The commit URLs on that page look like <https://github.com//commit/f13c0414e35400fb1e1691f37407f5cb084ff884#Formula/emacs.rb>; the repo name `Homebrew/homebrew-core` is clearly missing from the URL.

I briefly looked at the codebase, and it seems that the problem lies in `FormulaeController#select_repository`. Unless the formula is a dupe, resulting in a URL like http://braumeister.org/repos/Homebrew/homebrew-apache/formula/ab, a regular formula URL like http://braumeister.org/formula/emacs has no `params[:repository_id]`, so `@repository` is `nil`, and consequently `FormulaeHelper#name` is also `nil`.

**Comment by zmwangx** [comment]
By the way, a quick fix would be replacing

```ruby
"https://github.com/#{name}/commit/#{rev.sha}##{@formula.path}"
```

with

```ruby
"https://github.com/#{@formula.repository.name}/commit/#{rev.sha}##{@formula.path}"
```

But I suspect controller logic may need some work to fix or prevent related problems (which I'm not aware of).

**Comment by koraktor** [comment]
Thanks for the hint, I‘ll have a look.
