### ISSUE TITLE
HDF5 has a new version 1_2 which needs to be updated in config.hpp

### ISSUE THREAD

**Issue by mcheema** [koraktor/braumeister.org#50]
config.hpp in armadillo_bits nees to point to /usr/local/Cellar/hdf5/1.10.1_2

**Comment by koraktor** [comment]
Issues regarding individual formulae should be reported at [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) (or the corresponding taps).

In this case you’re probably referring to the `armadillo` formula which resides in [Homebrew/homebrew-science](https://github.com/Homebrew/homebrew-science). Please also note that formulae don’t usually change the source code (e.g. `config.hpp` mentioned above) of the projects they install.
